version: "3.8"

services:
    openwebui:
        image: ghcr.io/open-webui/open-webui:latest
        container_name: openwebui
        ports:
            - "8080:8080"
        environment:
            ENABLE_AUTO_UPDATE: "true"
            AUTO_UPDATE_INTERVAL: "3600"
            OLLAMA_API_BASE_URL: "http://172.22.128.1:11434"
        volumes:
            - openwebui_data:/app/backend/data
        restart: always

volumes:
    openwebui_data:
        driver: local
